// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rBcULC5Hn8rnDrAaZwq3LA
// Component: KMrQOaCrblv
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { DataFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: ae7V86eNoXA/codeComponent

import { useScreenVariants as useScreenVariantsaSn38CBljAy8D } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: aSN38cBljAy8D/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_pf_2022.module.css"; // plasmic-import: rBcULC5Hn8rnDrAaZwq3LA/projectcss
import sty from "./PlasmicRestApiFetcherWp2.module.css"; // plasmic-import: KMrQOaCrblv/css

export type PlasmicRestApiFetcherWp2__VariantMembers = {};
export type PlasmicRestApiFetcherWp2__VariantsArgs = {};
type VariantPropType = keyof PlasmicRestApiFetcherWp2__VariantsArgs;
export const PlasmicRestApiFetcherWp2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicRestApiFetcherWp2__ArgsType = {};
type ArgPropType = keyof PlasmicRestApiFetcherWp2__ArgsType;
export const PlasmicRestApiFetcherWp2__ArgProps = new Array<ArgPropType>();

export type PlasmicRestApiFetcherWp2__OverridesType = {
  pageContainer?: p.Flex<"div">;
  projectsContainer?: p.Flex<"div">;
  projectsFetcher?: p.Flex<typeof DataFetcher>;
  freeBox?: p.Flex<"div">;
  featuredImageFetcher?: p.Flex<typeof DataFetcher>;
  project?: p.Flex<"div">;
  description?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  p?: p.Flex<"p">;
  productTypes?: p.Flex<"div">;
  span?: p.Flex<"span">;
  projectImages?: p.Flex<"div">;
  projectImage?: p.Flex<"div">;
  httpApiFetcher?: p.Flex<typeof DataFetcher>;
};

export interface DefaultRestApiFetcherWp2Props {
  className?: string;
}

function PlasmicRestApiFetcherWp2__RenderFunc(props: {
  variants: PlasmicRestApiFetcherWp2__VariantsArgs;
  args: PlasmicRestApiFetcherWp2__ArgsType;
  overrides: PlasmicRestApiFetcherWp2__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsaSn38CBljAy8D()
  });

  return (
    <React.Fragment>
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"pageContainer"}
            data-plasmic-override={overrides.pageContainer}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              sty.pageContainer
            )}
          >
            <div
              data-plasmic-name={"projectsContainer"}
              data-plasmic-override={overrides.projectsContainer}
              className={classNames(projectcss.all, sty.projectsContainer)}
            >
              <DataFetcher
                data-plasmic-name={"projectsFetcher"}
                data-plasmic-override={overrides.projectsFetcher}
                className={classNames("__wab_instance", sty.projectsFetcher)}
                dataName={"fetchedData" as const}
                errorDisplay={
                  <ph.DataCtxReader>
                    {$ctx => "Error fetching data"}
                  </ph.DataCtxReader>
                }
                headers={{
                  "Content-Type": "application/json",
                  Accept: "application/json"
                }}
                loadingDisplay={
                  <ph.DataCtxReader>{$ctx => "Loading..."}</ph.DataCtxReader>
                }
                method={"GET" as const}
                noLayout={false}
                queryKey={"" as const}
                url={
                  "https://polymessa.com/wp-json/wp/v2/project?per_page=100" as const
                }
              >
                <ph.DataCtxReader>
                  {$ctx =>
                    true
                      ? (() => {
                          try {
                            return $ctx.fetchedData;
                          } catch (e) {
                            if (e instanceof TypeError) {
                              return [];
                            }
                            throw e;
                          }
                        })().map((currentItem, currentIndex) => (
                          <div
                            data-plasmic-name={"freeBox"}
                            data-plasmic-override={overrides.freeBox}
                            className={classNames(projectcss.all, sty.freeBox)}
                            key={currentIndex}
                          >
                            <DataFetcher
                              data-plasmic-name={"featuredImageFetcher"}
                              data-plasmic-override={
                                overrides.featuredImageFetcher
                              }
                              className={classNames(
                                "__wab_instance",
                                sty.featuredImageFetcher
                              )}
                              dataName={"fetchedData" as const}
                              errorDisplay={
                                <ph.DataCtxReader>
                                  {$ctx => "Error fetching data"}
                                </ph.DataCtxReader>
                              }
                              headers={{
                                "Content-Type": "application/json",
                                Accept: "application/json"
                              }}
                              loadingDisplay={
                                <ph.DataCtxReader>
                                  {$ctx => "Loading..."}
                                </ph.DataCtxReader>
                              }
                              method={"GET" as const}
                              noLayout={false}
                              queryKey={"" as const}
                              url={(() => {
                                try {
                                  return `https://polymessa.com/wp-json/wp/v2/media/${currentItem.featured_media}`;
                                } catch (e) {
                                  if (e instanceof TypeError) {
                                    return "https://polymessa.com/wp-json/wp/v2/media/87";
                                  }
                                  throw e;
                                }
                              })()}
                            >
                              <ph.DataCtxReader>
                                {$ctx =>
                                  true ? (
                                    <div
                                      data-plasmic-name={"project"}
                                      data-plasmic-override={overrides.project}
                                      className={classNames(
                                        projectcss.all,
                                        sty.project
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img___5Mam)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"100%" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"100%" as const}
                                        loading={"lazy" as const}
                                        src={(() => {
                                          try {
                                            return `https://polymessa.com${$ctx.fetchedData.source_url}`;
                                          } catch (e) {
                                            if (e instanceof TypeError) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })()}
                                      />

                                      {true ? (
                                        <div
                                          data-plasmic-name={"description"}
                                          data-plasmic-override={
                                            overrides.description
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            sty.description
                                          )}
                                        >
                                          <h1
                                            data-plasmic-name={"h1"}
                                            data-plasmic-override={overrides.h1}
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.h1,
                                              projectcss.__wab_text,
                                              sty.h1
                                            )}
                                          >
                                            {(() => {
                                              try {
                                                return currentItem.title
                                                  .rendered;
                                              } catch (e) {
                                                if (e instanceof TypeError) {
                                                  return "Enter some text";
                                                }
                                                throw e;
                                              }
                                            })()}
                                          </h1>

                                          <p
                                            data-plasmic-name={"p"}
                                            data-plasmic-override={overrides.p}
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.p,
                                              projectcss.__wab_text,
                                              sty.p
                                            )}
                                          >
                                            <div
                                              className={
                                                projectcss.__wab_expr_html_text
                                              }
                                              dangerouslySetInnerHTML={{
                                                __html: (() => {
                                                  try {
                                                    return currentItem.acf
                                                      .description;
                                                  } catch (e) {
                                                    if (
                                                      e instanceof TypeError
                                                    ) {
                                                      return "Enter some text";
                                                    }
                                                    throw e;
                                                  }
                                                })()
                                              }}
                                            />
                                          </p>

                                          {true ? (
                                            <div
                                              data-plasmic-name={"productTypes"}
                                              data-plasmic-override={
                                                overrides.productTypes
                                              }
                                              className={classNames(
                                                projectcss.all,
                                                sty.productTypes
                                              )}
                                            >
                                              {(() => {
                                                try {
                                                  return currentItem.acf
                                                    .product;
                                                } catch (e) {
                                                  if (e instanceof TypeError) {
                                                    return [];
                                                  }
                                                  throw e;
                                                }
                                              })().map(
                                                (
                                                  currentProductType,
                                                  currentProductTypeIndex
                                                ) => (
                                                  <span
                                                    data-plasmic-name={"span"}
                                                    data-plasmic-override={
                                                      overrides.span
                                                    }
                                                    className={classNames(
                                                      projectcss.all,
                                                      projectcss.span,
                                                      projectcss.__wab_text,
                                                      sty.span
                                                    )}
                                                    key={
                                                      currentProductTypeIndex
                                                    }
                                                  >
                                                    {(() => {
                                                      try {
                                                        return `${currentProductType}, `;
                                                      } catch (e) {
                                                        if (
                                                          e instanceof TypeError
                                                        ) {
                                                          return "Enter some text";
                                                        }
                                                        throw e;
                                                      }
                                                    })()}
                                                  </span>
                                                )
                                              )}
                                            </div>
                                          ) : null}
                                        </div>
                                      ) : null}
                                      {true ? (
                                        <div
                                          data-plasmic-name={"projectImages"}
                                          data-plasmic-override={
                                            overrides.projectImages
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            sty.projectImages
                                          )}
                                        >
                                          {true
                                            ? (() => {
                                                try {
                                                  return currentItem.acf.slides;
                                                } catch (e) {
                                                  if (e instanceof TypeError) {
                                                    return [];
                                                  }
                                                  throw e;
                                                }
                                              })().map(
                                                (
                                                  currentProjectImage,
                                                  currentProjectImageIndex
                                                ) => (
                                                  <div
                                                    data-plasmic-name={
                                                      "projectImage"
                                                    }
                                                    data-plasmic-override={
                                                      overrides.projectImage
                                                    }
                                                    className={classNames(
                                                      projectcss.all,
                                                      sty.projectImage
                                                    )}
                                                    key={
                                                      currentProjectImageIndex
                                                    }
                                                  >
                                                    <DataFetcher
                                                      data-plasmic-name={
                                                        "httpApiFetcher"
                                                      }
                                                      data-plasmic-override={
                                                        overrides.httpApiFetcher
                                                      }
                                                      className={classNames(
                                                        "__wab_instance",
                                                        sty.httpApiFetcher
                                                      )}
                                                      dataName={
                                                        "fetchedData" as const
                                                      }
                                                      errorDisplay={
                                                        <ph.DataCtxReader>
                                                          {$ctx =>
                                                            "Error fetching data"
                                                          }
                                                        </ph.DataCtxReader>
                                                      }
                                                      headers={{
                                                        "Content-Type":
                                                          "application/json",
                                                        Accept:
                                                          "application/json"
                                                      }}
                                                      loadingDisplay={
                                                        <ph.DataCtxReader>
                                                          {$ctx => "Loading..."}
                                                        </ph.DataCtxReader>
                                                      }
                                                      method={"GET" as const}
                                                      noLayout={false}
                                                      url={(() => {
                                                        try {
                                                          return `https://polymessa.com/wp-json/wp/v2/media/${currentProjectImage.field_5373e0e2a98e6}`;
                                                        } catch (e) {
                                                          if (
                                                            e instanceof
                                                            TypeError
                                                          ) {
                                                            return "https://api.github.com/users/plasmicapp/repos";
                                                          }
                                                          throw e;
                                                        }
                                                      })()}
                                                    >
                                                      <ph.DataCtxReader>
                                                        {$ctx => (
                                                          <p.PlasmicImg
                                                            alt={""}
                                                            className={classNames(
                                                              sty.img__j22L
                                                            )}
                                                            displayHeight={
                                                              "auto" as const
                                                            }
                                                            displayMaxHeight={
                                                              "none" as const
                                                            }
                                                            displayMaxWidth={
                                                              "120px" as const
                                                            }
                                                            displayMinHeight={
                                                              "0" as const
                                                            }
                                                            displayMinWidth={
                                                              "0" as const
                                                            }
                                                            displayWidth={
                                                              "auto" as const
                                                            }
                                                            loading={
                                                              "lazy" as const
                                                            }
                                                            src={(() => {
                                                              try {
                                                                return `https://polymessa.com${$ctx.fetchedData.source_url}`;
                                                              } catch (e) {
                                                                if (
                                                                  e instanceof
                                                                  TypeError
                                                                ) {
                                                                  return undefined;
                                                                }
                                                                throw e;
                                                              }
                                                            })()}
                                                          />
                                                        )}
                                                      </ph.DataCtxReader>
                                                    </DataFetcher>
                                                  </div>
                                                )
                                              )
                                            : null}
                                        </div>
                                      ) : null}
                                    </div>
                                  ) : null
                                }
                              </ph.DataCtxReader>
                            </DataFetcher>
                          </div>
                        ))
                      : null
                  }
                </ph.DataCtxReader>
              </DataFetcher>
            </div>
          </div>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  pageContainer: [
    "pageContainer",
    "projectsContainer",
    "projectsFetcher",
    "freeBox",
    "featuredImageFetcher",
    "project",
    "description",
    "h1",
    "p",
    "productTypes",
    "span",
    "projectImages",
    "projectImage",
    "httpApiFetcher"
  ],
  projectsContainer: [
    "projectsContainer",
    "projectsFetcher",
    "freeBox",
    "featuredImageFetcher",
    "project",
    "description",
    "h1",
    "p",
    "productTypes",
    "span",
    "projectImages",
    "projectImage",
    "httpApiFetcher"
  ],
  projectsFetcher: [
    "projectsFetcher",
    "freeBox",
    "featuredImageFetcher",
    "project",
    "description",
    "h1",
    "p",
    "productTypes",
    "span",
    "projectImages",
    "projectImage",
    "httpApiFetcher"
  ],
  freeBox: [
    "freeBox",
    "featuredImageFetcher",
    "project",
    "description",
    "h1",
    "p",
    "productTypes",
    "span",
    "projectImages",
    "projectImage",
    "httpApiFetcher"
  ],
  featuredImageFetcher: [
    "featuredImageFetcher",
    "project",
    "description",
    "h1",
    "p",
    "productTypes",
    "span",
    "projectImages",
    "projectImage",
    "httpApiFetcher"
  ],
  project: [
    "project",
    "description",
    "h1",
    "p",
    "productTypes",
    "span",
    "projectImages",
    "projectImage",
    "httpApiFetcher"
  ],
  description: ["description", "h1", "p", "productTypes", "span"],
  h1: ["h1"],
  p: ["p"],
  productTypes: ["productTypes", "span"],
  span: ["span"],
  projectImages: ["projectImages", "projectImage", "httpApiFetcher"],
  projectImage: ["projectImage", "httpApiFetcher"],
  httpApiFetcher: ["httpApiFetcher"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  pageContainer: "div";
  projectsContainer: "div";
  projectsFetcher: typeof DataFetcher;
  freeBox: "div";
  featuredImageFetcher: typeof DataFetcher;
  project: "div";
  description: "div";
  h1: "h1";
  p: "p";
  productTypes: "div";
  span: "span";
  projectImages: "div";
  projectImage: "div";
  httpApiFetcher: typeof DataFetcher;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRestApiFetcherWp2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRestApiFetcherWp2__VariantsArgs;
    args?: PlasmicRestApiFetcherWp2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRestApiFetcherWp2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRestApiFetcherWp2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRestApiFetcherWp2__ArgProps,
          internalVariantPropNames: PlasmicRestApiFetcherWp2__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicRestApiFetcherWp2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "pageContainer") {
    func.displayName = "PlasmicRestApiFetcherWp2";
  } else {
    func.displayName = `PlasmicRestApiFetcherWp2.${nodeName}`;
  }
  return func;
}

export const PlasmicRestApiFetcherWp2 = Object.assign(
  // Top-level PlasmicRestApiFetcherWp2 renders the root element
  makeNodeComponent("pageContainer"),
  {
    // Helper components rendering sub-elements
    projectsContainer: makeNodeComponent("projectsContainer"),
    projectsFetcher: makeNodeComponent("projectsFetcher"),
    freeBox: makeNodeComponent("freeBox"),
    featuredImageFetcher: makeNodeComponent("featuredImageFetcher"),
    project: makeNodeComponent("project"),
    description: makeNodeComponent("description"),
    h1: makeNodeComponent("h1"),
    p: makeNodeComponent("p"),
    productTypes: makeNodeComponent("productTypes"),
    span: makeNodeComponent("span"),
    projectImages: makeNodeComponent("projectImages"),
    projectImage: makeNodeComponent("projectImage"),
    httpApiFetcher: makeNodeComponent("httpApiFetcher"),

    // Metadata about props expected for PlasmicRestApiFetcherWp2
    internalVariantProps: PlasmicRestApiFetcherWp2__VariantProps,
    internalArgProps: PlasmicRestApiFetcherWp2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRestApiFetcherWp2;
/* prettier-ignore-end */
